// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args1
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: { //You can add static templates here
    'default': '{0}: {1}',
    'defaultAlt': '{0}',
    'print': '<pre>{0}</pre>',
    'example:important': '<h1>^2{0}</h1>',
    'win': '<div id="message-style"><div id="obj"> <div id="top-obj"> <div id="head-obj"> <i class="{1}" style="color: {0}"></i><span id="header" style="color: {0}">{2}</span></div><span id="time">{4}</span></div><div id="bottom-obj"><br><div id="message">{3}</div></div></div></div>'
  },
  fadeTimeout: 7000,
  suggestionLimit: 5,
  style: {
    background: 'rgba(52, 73, 94, 0.7)',
    width: '38%',
    height: '22%',
  }
};
